[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "cmcomponents"
version = "0.1.0"
description = "Components to run models in CellModeller."
readme = "README.md"
license = "BSD-3-Clause"
license-files = ["licence.txt"]
requires-python = ">=3"
authors = [
    {name = "Tim Rudge"},
    {name = "PJ Steiner"},
    {name = "Jim Haseloff"},
]
dependencies = [
    "numpy",
    "scipy",
    "pyopencl",
    "setuptools",
    "CellModeller @ git+https://github.com/cellmodeller/CellModeller.git@feature/tim/repo-split",
]

[project.urls]
Homepage = "https://github.com/cellmodeller/CMComponents"
Repository = "https://github.com/cellmodeller/CMComponents"

[tool.setuptools.packages.find]
include = ["cmcomponents*"]

[tool.setuptools.package-data]
cmcomponents = ["*.cl", "*/*.cl", "*/*/*.cl"]
